CREATE TABLE Usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR2(50) NOT NULL UNIQUE,
    correo VARCHAR2(100) NOT NULL UNIQUE,
    contrasena VARCHAR2(255) NOT NULL
);

CREATE TABLE Recetas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    tipo_de_cocina VARCHAR2(50) NOT NULL,
    ingredientes CLOB NOT NULL,
    pais_de_origen VARCHAR2(50) NOT NULL,
    dificultad VARCHAR2(20) NOT NULL,
    instrucciones CLOB NOT NULL,
    tiempo_de_coccion VARCHAR2(20) NOT NULL,
    imagen_url VARCHAR2(255)
);

INSERT INTO
    Usuarios (nombre_usuario, correo, contrasena)
VALUES
    (
        'jose.gonzalez',
        'jose.gonzalez@gmail.com',
        'password1'
    );

INSERT INTO
    Usuarios (nombre_usuario, correo, contrasena)
VALUES
    (
        'maria.perez',
        'maria.perez@gmail.com',
        'password2'
    );

INSERT INTO
    Usuarios (nombre_usuario, correo, contrasena)
VALUES
    (
        'juan.rodriguez',
        'juan.rodriguez@gmail.com',
        'password3'
    );

INSERT INTO
    Usuarios (nombre_usuario, correo, contrasena)
VALUES
    (
        'ana.sanchez',
        'ana.sanchez@gmail.com',
        'password4'
    );

INSERT INTO
    Usuarios (nombre_usuario, correo, contrasena)
VALUES
    (
        'carlos.lopez',
        'carlos.lopez@gmail.com',
        'password5'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Cazuela de Vacuno',
        'Comida Chilena',
        'Carne de vacuno, Papas, Zapallo, Zanahorias, Maíz, Arvejas, Cebolla, Ajo, Sal, Pimienta',
        'Chile',
        'Mediana',
        '1- Sofreír la cebolla y el ajo.\2. Añadir la carne y dorar.\n3. Agregar las verduras y cubrir con agua.\n4. Cocinar hasta que todo esté tierno.',
        '1 hora 30 minutos',
        '/images/cazuela_vacuno.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Empanadas de Pino',
        'Comida Chilena',
        'Masa para empanadas, Carne molida, Cebolla, Aceitunas, Pasas, Huevos duros, Comino, Sal, Pimienta',
        'Chile',
        'Difícil',
        '1. Preparar el pino cocinando la carne con cebolla y especias.\n2. Enrollar la masa y rellenar con el pino.\n3. Agregar aceitunas, pasas y huevo duro.\n4. Cocinar al horno hasta dorar.',
        '45 minutos',
        '/images/empanadas_pino.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Completo Italiano',
        'Comida Chilena',
        'Pan para completo, Salchicha, Tomate, Mayonesa, Palta, Limón, Salsa de ají',
        'Chile',
        'Fácil',
        '1. Hervir la salchicha hasta que esté cocida.\n2. Abrir el pan y agregar la salchicha.\n3. Añadir tomate picado, mayonesa, palta y un chorrito de limón.',
        '15 minutos',
        '/images/completo_italiano.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Chorrillana',
        'Comida Chilena',
        'Papas fritas, Carne de vacuno, Cebolla, Huevos, Sal, Pimienta',
        'Chile',
        'Mediana',
        '1. Freír las papas hasta que estén doradas.\n2. Sofreír la cebolla y la carne.\n3. Colocar la carne y la cebolla sobre las papas.\n4. Añadir huevos fritos por encima.',
        '30 minutos',
        '/images/chorrillana.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Mote con Huesillos',
        'Bebida Chilena',
        'Mote (trigo cocido), Huesillos (duraznos deshidratados), Agua, Azúcar, Canela',
        'Chile',
        'Fácil',
        '1. Hervir los huesillos hasta que estén suaves.\n2. Enfriar los huesillos.\n3. Servir los huesillos en agua con mote y endulzar al gusto.\n4. Añadir canela.',
        '1 hora',
        '/images/mote_huesillos.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Sopaipillas con Pebre',
        'Comida Chilena',
        'Harina, Manteca, Agua, Sal, Aceite para freír, Tomate, Cebolla, Cilantro, Ají',
        'Chile',
        'Mediana',
        '1. Preparar la masa con harina, manteca, agua y sal.\n2. Formar las sopaipillas y freírlas hasta que estén doradas.\n3. Preparar el pebre mezclando tomate, cebolla, cilantro y ají picados.',
        '45 minutos',
        '/images/sopaipillas_pebre.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Paila Marina',
        'Comida Chilena',
        'Mariscos variados, Tomate, Cebolla, Ajo, Papas, Caldo de pescado, Sal, Pimienta, Perejil',
        'Chile',
        'Difícil',
        '1. Sofreír cebolla y ajo.\n2. Añadir tomates y cocinar hasta reducir.\n3. Agregar mariscos y caldo.\n4. Cocinar a fuego lento hasta que los mariscos estén cocidos.\n5. Añadir papas y perejil antes de servir.',
        '1 hora',
        '/images/paila_marina.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Pisco Sour',
        'Bebida Chilena',
        'Pisco, Jugo de limón, Azúcar, Clara de huevo, Hielo, Amargo de Angostura',
        'Chile',
        'Fácil',
        '1. Mezclar pisco, jugo de limón y azúcar en una coctelera con hielo.\n2. Añadir la clara de huevo y agitar vigorosamente.\n3. Servir en un vaso y añadir unas gotas de amargo de Angostura por encima.',
        '10 minutos',
        '/images/pisco_sour.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Humitas en Chala',
        'Comida Chilena',
        'Choclo fresco, Cebolla, Aceite, Mantequilla, Sal, Pimienta, Chile picante (opcional)',
        'Chile',
        'Mediana',
        '1. Moler el choclo junto con la cebolla.\n2. Sofreír la mezcla con aceite y mantequilla, sazonar al gusto.\n3. Colocar la mezcla en chalas (hojas de maíz) y envolverlas.\n4. Cocinar al vapor durante aproximadamente 45 minutos.',
        '1 hora',
        '/images/humitas_chala.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Kuchen de Manzana',
        'Postre Chileno',
        'Harina, Manteca, Azúcar, Huevos, Manzanas, Canela, Levadura, Sal',
        'Chile',
        'Mediana',
        '1. Preparar la masa mezclando harina, manteca, azúcar, huevos, levadura y sal.\n2. Extender la masa en un molde.\n3. Añadir manzanas peladas y cortadas, espolvorear con canela.\n4. Hornear hasta que la masa esté dorada y las manzanas cocidas.',
        '1 hora 15 minutos',
        '/images/kuchen_manzana.jpg'
    );

INSERT INTO
    Recetas (
        titulo,
        tipo_de_cocina,
        ingredientes,
        pais_de_origen,
        dificultad,
        instrucciones,
        tiempo_de_coccion,
        imagen_url
    )
VALUES
    (
        'Curanto en Olla',
        'Comida Chilena',
        'Mariscos, Carne de cerdo, Pollo, Papas, Cebolla, Repollo, Zanahorias, Ajo, Sal, Pimienta',
        'Chile',
        'Difícil',
        '1. En una olla grande, colocar capas de mariscos, carne de cerdo y pollo.\n2. Añadir las verduras y sazonar con sal y pimienta.\n3. Cubrir con agua y cocinar a fuego lento durante varias horas hasta que todo esté tierno.\n4. Servir caliente.',
        '2 horas',
        '/images/curanto_olla.jpg'
    );

ALTER TABLE
    Recetas
ADD
    ingredientes_temp VARCHAR2(4000);

UPDATE
    Recetas
SET
    ingredientes_temp = ingredientes;

ALTER TABLE
    Recetas DROP COLUMN ingredientes;

ALTER TABLE
    Recetas RENAME COLUMN ingredientes_temp TO ingredientes;

ALTER TABLE
    Recetas
ADD
    descripcion VARCHAR2(1000);

UPDATE
    Recetas
SET
    descripcion = 'Un reconfortante guiso chileno con carne y verduras, perfecto para días fríos.'
WHERE
    titulo = 'Cazuela de Vacuno';

UPDATE
    Recetas
SET
    descripcion = 'Empanadas tradicionales rellenas de carne, cebolla y especias, horneadas hasta dorar.'
WHERE
    titulo = 'Empanadas de Pino';

UPDATE
    Recetas
SET
    descripcion = 'Un hot dog chileno con tomate, mayonesa y palta, ideal para una comida rápida.'
WHERE
    titulo = 'Completo Italiano';

UPDATE
    Recetas
SET
    descripcion = 'Papas fritas cubiertas con carne, cebolla y huevos, una combinación perfecta para compartir.'
WHERE
    titulo = 'Chorrillana';

UPDATE
    Recetas
SET
    descripcion = 'Postre refrescante de mote y duraznos en almíbar, popular en verano.'
WHERE
    titulo = 'Mote con Huesillos';

UPDATE
    Recetas
SET
    descripcion = 'Masa frita acompañada de pebre, un aperitivo típico chileno.'
WHERE
    titulo = 'Sopaipillas con Pebre';

UPDATE
    Recetas
SET
    descripcion = 'Sopa de mariscos chilenos, ideal para amantes de los frutos del mar.'
WHERE
    titulo = 'Paila Marina';

UPDATE
    Recetas
SET
    descripcion = 'Cóctel tradicional chileno a base de pisco, limón y un toque de amargo.'
WHERE
    titulo = 'Pisco Sour';

UPDATE
    Recetas
SET
    descripcion = 'Pasta de choclo envuelta en hojas de maíz, cocinada al vapor.'
WHERE
    titulo = 'Humitas';

UPDATE
    Recetas
SET
    descripcion = 'Tarta de manzana chilena, dulce y aromática, perfecta para el té.'
WHERE
    titulo = 'Kuchen de Manzana';

UPDATE
    Recetas
SET
    descripcion = 'Un plato abundante de carnes y mariscos cocidos lentamente en una olla.'
WHERE
    titulo = 'Curanto en Olla';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Cazuela de Vacuno';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Empanadas de Pino';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Completo Italiano';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Chorrillana';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Mote con Huesillos';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Sopaipillas con Pebre';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Paila Marina';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Pisco Sour';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Humitas';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Kuchen de Manzana';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(REPLACE(instrucciones, '\n', ' '), '1.', '1-')
WHERE
    titulo = 'Curanto en Olla';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Cazuela de Vacuno';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Empanadas de Pino';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Completo Italiano';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Chorrillana';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Mote con Huesillos';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Sopaipillas con Pebre';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Paila Marina';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Pisco Sour';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Humitas';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Kuchen de Manzana';

UPDATE
    Recetas
SET
    instrucciones = REPLACE(
        REPLACE(
            REPLACE(REPLACE(instrucciones, '2.', '2-'), '3.', '3-'),
            '4.',
            '4-'
        ),
        '5.',
        '5-'
    )
WHERE
    titulo = 'Curanto en Olla';

ALTER TABLE
    Usuarios
ADD
    roles VARCHAR2(25);

UPDATE
    usuarios
SET
    roles = 'admin'
WHERE
    id = 1;

UPDATE
    usuarios
SET
    roles = 'admin'
WHERE
    id = 2;

UPDATE
    usuarios
SET
    roles = 'usuario'
WHERE
    id = 3;

UPDATE
    usuarios
SET
    roles = 'usuario'
WHERE
    id = 4;

UPDATE
    usuarios
SET
    roles = 'usuario'
WHERE
    id = 5;

UPDATE
    usuarios
SET
    contrasena = '$2a$12$Hg.lFDN4Inpy5II.ZnbSKeQNt6qE5x0J91XO8xsh7.m2eeSScbW/W'
WHERE
    id = 1;

UPDATE
    usuarios
SET
    contrasena = '$2a$12$yv9oyZq4j1Aa0M61XtFNze.QllY4.jYFEafMj5HKHKUa8o39jgdwm'
WHERE
    id = 2;

UPDATE
    usuarios
SET
    contrasena = '$2a$12$yM14B5EF5dIr.XgChAQwz.JEbQf2AxH2VgHxTkDQl6VbFtP4VX4V2'
WHERE
    id = 3;

UPDATE
    usuarios
SET
    contrasena = '$2a$12$QwZAbpgvQMZzQaLx0lz5Z.BVu62ez9Uh7vi673wSp2svR3nyiG782'
WHERE
    id = 4;

UPDATE
    usuarios
SET
    contrasena = '$2a$12$06VZ0nR/0cRYA/3JPlywt.PrwNUiSV8uM4g5xxvqx8ec.C2talfDe'
WHERE
    id = 5;

/* CREACION DE NUEVAS TABLAS PARA LA SUMATIVA NUMERO 2 */
CREATE TABLE receta_fotos (
    receta_id NUMBER(19, 0) NOT NULL,
    foto_url VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT fk_receta_fotos FOREIGN KEY (receta_id) REFERENCES recetas (id) ON DELETE CASCADE
);

CREATE TABLE receta_videos (
    receta_id NUMBER(19, 0) NOT NULL,
    video_url VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT fk_receta_videos FOREIGN KEY (receta_id) REFERENCES recetas (id) ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto CLOB NOT NULL,
    valoracion NUMBER(1) CHECK (
        valoracion BETWEEN 1
        AND 5
    ) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    receta_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_receta FOREIGN KEY (receta_id) REFERENCES recetas(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

ALTER TABLE
    COMENTARIOS RENAME TO COMENTARIO;

-- Modificar longitud de las columnas URL
ALTER TABLE receta_fotos MODIFY foto_url VARCHAR2(2083 CHAR);
ALTER TABLE receta_videos MODIFY video_url VARCHAR2(2083 CHAR);

-- Crear índices para mejorar el rendimiento de las consultas
CREATE INDEX idx_receta_fotos_receta_id ON receta_fotos (receta_id);
CREATE INDEX idx_receta_videos_receta_id ON receta_videos (receta_id);

-- Agregar restricciones únicas para evitar duplicados
ALTER TABLE receta_fotos ADD CONSTRAINT unique_foto_url UNIQUE (receta_id, foto_url);
ALTER TABLE receta_videos ADD CONSTRAINT unique_video_url UNIQUE (receta_id, video_url);
